const BlogData = [
    {
        image: require('../../assets/img/blog1.png'),
      date: '30 Nov 24',
      tag: 'e-Crop',
      title: 'Introduction to Smart Farming: How e-Crop is Transforming Agriculture',
      desc: 'The Food and Agriculture Organization (FAO) estimates that by 2050, global food production ...',
      author: 'Amarben Patni',
      avatar: 'https://fakeimg.pl/35x35/?text=SC',
      comments: 35,
      detailPage: '/Introduction_to_Smart_Farming_How_e-Crop_is_Transforming_Agriculture', // File name for the blog detail
    },
    {
      image: require('../../assets/img/Boost Profits with Precision Farming e-Crop in Action.webp'),
    date: '1 Dec 24',
    tag: 'e-Crop',
    title: 'Boost Profits with Precision Farming: e-Crop in Action',
    desc: 'In this modern world of farming, farmers are always looking for new ideas to grow more...',
    author: 'Amarben Patni',
    avatar: 'https://fakeimg.pl/35x35/?text=SC',
    comments: 32,
    detailPage: '/Boost_profits_with_precision_farming_ecrop_action', // File name for the blog detail
  },
  {
    image: require('../../assets/img/e-Crop The Ultimate IoT Solution for Precision Agriculture in 2024.webp'),
  date: '3 Dec 24',
  tag: 'e-Crop',
  title: 'e-Crop: The Ultimate IoT Solution for Precision Agriculture in 2024',
  desc: 'The global agricultural landscape is undergoing innovative transformation, inspired by the immediate...',
  author: 'Amarben Patni',
  avatar: 'https://fakeimg.pl/35x35/?text=SC',
  comments: 32,
  detailPage: '/Ecrop_The_Ultimate_IoT_Solution_For_Precision_Agriculture_In_2024', // File name for the blog detail
},
  {
    image: require('../../assets/img/e-Crop’s Role in Meeting Global Food Security Goals by 2030.webp'),
  date: '5 Dec 24',
  tag: 'e-Crop',
  title: 'e-Crop’s Role in Meeting Global Food Security Goals by 2030 ',
  desc: 'The Global Hunger Index means oversight of whether countries are attaining hunger-associated...',
  author: 'Amarben Patni',
  avatar: 'https://fakeimg.pl/35x35/?text=SC',
  comments: 32,
  detailPage: '/Ecrops_Role_In_Meeting_Global_Food_Security_Goals_By_2030', // File name for the blog detail
},
{
  image: require('../../assets/img/Empowering Small Farmers e-Crop’s Affordable Precision Farming Solutions..webp'),
date: '7 Dec 24',
tag: 'e-Crop',
title: 'Empowering Small Farmers: e-Crop’s Affordable Precision Farming Solutions. ',
desc: 'India needs a focus on farmers with small landholdings and establish a strategy to increase...',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/Empowering_Small_Farmers_Ecrops_Affordable_Precision_Farming_Solutions', // File name for the blog detail
},
{
  image: require('../../assets/img/How e-Crop is Revolutionizing Modern Farming Practices.webp'),
date: '9 Dec 24',
tag: 'e-Crop',
title: 'How e-Crop is Revolutionizing Modern Farming Practices',
desc: 'e-Crop is leading the revolution in modern agriculture by integrating technology into agriculture...',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/How_Ecrop_Is_Revolutionizing_Modern_Farming_Practices',
},
{
  image: require('../../assets/img/Bridging_Gaps_in_Agriculture_eCrops_Role_from_State_to_Panchayat_Levels1.webp'),
date: '11 Dec 24',
tag: 'e-Crop',
title: 'Bridging Gaps in Agriculture: e-Crop’s Role from State to Panchayat Levels',
desc: 'The kind of world where food security is becoming more of an issue, adjustments have to be made...',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/Bridging_Gaps_In_Agriculture_Ecrops_Role_From_State_To_Panchayat_Levels',
},
{
  image: require('../../assets/img/Cut Fertilizer Costs with e-Crop An Essential for Modern Farming-1.webp'),
date: '12 Dec 24',
tag: 'e-Crop',
title: 'Cut Fertilizer Costs with e-Crop: An Essential for Modern Farming',
desc: 'What if the secret to saving money on fertilizers was just a click away? Enter the world...',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/Cut_Fertilizer_Costs_With_Ecrop_Technology',
},
{
  image: require('../../assets/img/Invest in Sustainable Farming with e-Crop The Future of Eco-Friendly Agriculture_1.webp'),
date: '13 Dec 24',
tag: 'e-Crop',
title: 'Invest in sustainable farming with e-Crop today',
desc: 'Day by day the world’s population is increasing, so to feed the world, increasing agricultural...',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/Invest_In_Sustainable_Farming_With_Ecrop_Today',
},
{
  image: require('../../assets/img/A Comprehensive Look at e-Crop From Soil Data to Harvest Insights-1.webp'),
date: '13 Dec 24',
tag: 'e-Crop',
title: 'A Comprehensive Look at e-Crop: From Soil Data to Harvest Insights',
desc: 'Explore the powerful e-Crop device for modern agriculture. Learn how it provides critical soil data....',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/Comprehensive_look_at_ecrop_soil_data_to_harvest_insights',
},
{
  image: require('../../assets/img/precision-farming-for-beginners-guide-to-using-e-crop-effectively-1.webp'),
date: '15 Dec 24',
tag: 'e-Crop',
title: 'Precision Farming for Beginners: A Guide to Using e-Crop Effectively',
desc: 'Discover how beginners can leverage e-Crop for precision farming. Learn how to set up, manage crops, and use data-driven insights to boost productivity....',
author: 'Amarben Patni',
avatar: 'https://fakeimg.pl/35x35/?text=SC',
comments: 3,
detailPage: '/precision_farming_for_beginners_guide_to_using_ecrop_effectively',
},
    // Add more blogs as needed
  ];
  
  export default BlogData;
  